ARG ECS_ACCOUNT_NUMBER
FROM ${ECS_ACCOUNT_NUMBER}.dkr.ecr.eu-west-2.amazonaws.com/eas-app-base:latest

ENV SERVICE=admin

# Create root directory and copy repo
COPY . $DIR_ADMIN

# Run emergency-alerts-admin
RUN python$PYTHON_VERSION -m venv $VENV_ADMIN && cd $DIR_ADMIN && . $VENV_ADMIN/bin/activate && \
    pip3 install wheel && make bootstrap

# Create a blank configuration file
RUN echo "" > $DIR_ADMIN/environment.sh

COPY scripts/start.sh /
CMD bash /start.sh

EXPOSE 6012
