version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo "No pre build commands"
  build:
    commands:
      - bash ./scripts/docker-build.sh --ENVIRONMENT development --IMAGE admin --ARGS '--push'
  post_build:
    commands:
      - echo "No post build commands"
