version: 0.2

phases:
  pre_build:
    commands:
      - echo "" > environment.sh
  build:
    commands:
      - apt-get install python3-dev
      - make bootstrap
      - make test
  post_build:
    commands:
      - echo "No post build commands"
