version: 0.2

phases:
  pre_build:
    commands:
      - echo "" > environment.sh
  build:
    commands:
      - apt-get -y install python3-dev
      - make bootstrap
      - printenv
      - cd $ADMIN_DIR && source $VENV_ADMIN/bin/activate && make test
  post_build:
    commands:
      - echo "No post build commands"
