name: admin-pr-checks

on:
  pull_request:
    branches:
      - main

jobs:
  run-test-script:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Run test script
        run: |
          export NOTIFY_ENVIRONMENT='development'
          export ENVIRONMENT='development'
          export FLASK_APP=application.py
          export FLASK_DEBUG=False
          export WERKZEUG_DEBUG_PIN=off
          make bootstrap
