name: on-pr-into-main

on:
  pull_request:
    branches:
      - main

jobs:
  run-pr-checks:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Rebuild nvm to specific version
        run: |
          rm -rf ~/.nvm
          nvm install 16.14.0
          nvm use 16.14.0
          nvm alias default 16.14.0

      - name: Install dependencies

      - name: Bootstrap Python app and run tests
        run: |
          export ENVIRONMENT='local'
          export ENCRYPTION_DANGEROUS_SALT='dev-notify-salt'
          export ENCRYPTION_SECRET_KEY='dev-notify-secret-key'
          export DANGEROUS_SALT='dev-notify-salt'
          export SECRET_KEY='dev-notify-secret-key'
          export ADMIN_CLIENT_SECRET='dev-notify-secret-key'
          export IN_CICD='True'
          export FLASK_APP=application.py
          set -eu
          make bootstrap-for-tests
          make test
