name: on-pr-into-main

env:
  PYTHON_VERSION: 3.9

on:
  pull_request:
    branches:
      - main

jobs:
  run-pr-checks:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Bootstrap Python app and run tests
        run: |
          export ENVIRONMENT='local'
          export ENCRYPTION_DANGEROUS_SALT='dev-notify-salt'
          export ENCRYPTION_SECRET_KEY='dev-notify-secret-key'
          export DANGEROUS_SALT='dev-notify-salt'
          export SECRET_KEY='dev-notify-secret-key'
          export ADMIN_CLIENT_SECRET='dev-notify-secret-key'
          export IN_CICD='True'
          export FLASK_APP=application.py
          set -eu
          make bootstrap-for-tests
