name: on-pr-into-main

env:
  NVM_VERSION: 0.39.7
  NODE_VERSION: 16.14.0
  PYTHON_VERSION: 3.9

on:
  pull_request:
    branches:
      - main

jobs:
  run-pr-checks:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install a specific nvm version
        run: |
          rm -rf $NVM_DIR
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v${{ env.NVM_VERSION }}/install.sh | bash

          cat ~/.bashrc | grep "NVM" > ~/.non-interactive

      - name: Install a specific node version
        run: |
          source ~/.non-interactive

          echo "NVM Version: $(nvm --version)"
          nvm install ${{ env.NODE_VERSION }}
          nvm use ${{ env.NODE_VERSION }}
          nvm alias default ${{ env.NODE_VERSION }}

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.0

      - name: Bootstrap Python app and run tests
        run: |
          source ~/.non-interactive

          export ENVIRONMENT='local'
          export ENCRYPTION_DANGEROUS_SALT='dev-notify-salt'
          export ENCRYPTION_SECRET_KEY='dev-notify-secret-key'
          export DANGEROUS_SALT='dev-notify-salt'
          export SECRET_KEY='dev-notify-secret-key'
          export ADMIN_CLIENT_SECRET='dev-notify-secret-key'
          export IN_CICD='True'
          export FLASK_APP=application.py
          set -eu
          make bootstrap-for-tests
          make test
